### PR TITLE
add popcorn time to list of projects using wcjs prebuilt

### PR DESCRIPTION
**Pull request by luigiplr**

### CODE REVIEW

**Comment by Ivshti** [comment]
Does pct use this as of right now? On the official download page?

**Comment by jaruba** [comment]
If so, you should probably push this to `WebChimera.js` too:
https://github.com/RSATom/WebChimera.js/blob/master/README.md#known-projects-using-webchimerajs

**Comment by luigiplr** [comment]
It will be soon & yes @jaruba ill make a PR for that aswell.

**Comment by Ivshti** [comment]
@luigiplr https://github.com/Ivshti/wcjs-prebuilt/commit/d952a638c8abfda321ff6fd7e9a284a3b82ceaa2

Can I close this?

**Comment by luigiplr** [comment]
@Ivshti Sure everything looks good.

**Pull request closed without merging**
