### PR TITLE
Fetch vlc from webchimera repo

### PR DESCRIPTION
**Pull request by guidupuy**
RSAtom now releases prebuilt versions of WebChimera with VLC included, so I feel there's no point in fetching VLC separately...

I've also improved logging with colors and clearer output messages:

capture d ecran 2016-05-12 a 11 09 23

### CODE REVIEW

**Comment by RSATom** [comment]
@Ivshti, it looks like you should give this guy direct commit access to repo...

**Comment by Ivshti** [comment]
@RSATom I haven't reviewed deeply, but I will.

**Comment by RSATom** [comment]
@Ivshti, it's just because he is the only who do something...
Maybe it worth move this repo to separate organization? Or maybe to @magics or @webchimera-org?

@guidupuy, are you ready be maintainer of this package?

**Comment by guidupuy** [comment]
@RSATom sure, why not? Be warned that I've never done that before though... ;-)

**Comment by RSATom** [comment]
@guidupuy, good. As I can see @Ivshti already gave you access to the repo, so you can start crash it...

The only question will be access to `npmjs` to publish new versions, but it depends on @Ivshti only...

**Pull request merged**
