### PR TITLE
use npm config & bugfix

### PR DESCRIPTION
**Pull request by tetsuyainfra**
1. Use npm config (.npmrc)
   ~~"find-project-root" module seach .git/svn folder in parent folder.~~
   ~~When there is a project folder in ~/Desktop or ~/foobar, and we have ~/.git/config file~~
   ~~it module detect rootdir with~/~~
   I made a mistaken, I didn't git init in my project. I'm so sorry.
2. bugfix in [install.js#L40](https://github.com/Ivshti/wcjs-prebuilt/blob/master/install.js#L40)
   `version: (data.version === 'latest') ? 'latest' : assetParsed[2],`
   to
   `version: (data.runtime.version === 'latest') ? 'latest' : assetParsed[2],`

if you don't mind, merge this code.

 #Sorry, I'm not good at English

### CODE REVIEW

**Comment by luigiplr** [comment]
This looks good! 

@Ivshti can you confirm the branch works on your use cases?

**Comment by RSATom** [comment]
it's remove ability config via `package.json`. right?

**Comment by tetsuyainfra** [comment]
@RSATom 
Yes ! thank you very much!

**Comment by RSATom** [comment]
@tetsuyainfra, I think we should keep ability configure via `package.json`

**Comment by tetsuyainfra** [comment]
I made a mistaken. so, i will make mini bugfix later.

**Pull request closed without merging**
